version: "3.8"
services:
  notebook:
    image: diegosp10/snpe_package:latest
    command: jupyter notebook --port 1111 --NotebookApp.open_browser=False --NotebookApp.ip='0.0.0.0' --allow-root --NotebookApp.notebook_dir=/snpe-package
    environment:
      - USER=$USER
      - TZ=America/New_York
    ports:
      - 1111:1111
    tty: true
    restart: always
    volumes:
      - type: bind
        source: ~/snpe-package
        target: /snpe-package
