name: Super-Linter & Automatic formatting

on: push

jobs: 
  lint-plus-format:
    name: lint_and_format
    runs-on: self-hosted
    strategy:
      fail-fast: false

    steps:

    - name: python_setup
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: install_dependencies
      run: pip install black isort

    - name: checkout_code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.FORMAT_TOKEN }}
 
    - name: super_linter
      continue-on-error: true
      uses: super-linter/super-linter@v5.0.0
      env:
        DEFAULT_BRANCH: main
        GITHUB_TOKEN: ${{ secrets.FORMAT_TOKEN }}
        VALIDATE_PYTHON_MYPY: true
        VALIDATE_PYTHON_BLACK: true
        VALIDATE_PYTHON_ISORT: true

    - name: run_black
      run: black .

    - name: run_isort
      run: isort . --profile black

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: modified by formatting pipeline 
        branch: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref }}
      
