# Same as testing-workflow.yml with slight changes:

# Removed linting tools as it's part of another workflow
# line 19 --> runs on: self-hosted (it will look for the self-hosted runner created by organization)
# line 36 --> installing hypothesis testing dependencies (for property testing)
# line 39 --> running pytest and hypothesis

name: Python package

on: push

jobs:
  build:

    runs-on: self-hosted
    strategy:
      fail-fast: false

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Test with pytest and hypothesis
      run: python dep_check.py
      
        
